rootProject.name = "SpringGuides"
include("rest-apis")
include("misc")
include("io")
include("data-access")
include("security")
include("messaging")
include("ops")
include("batch-processing")
include("web")
include("caching")
include("microservices")
include("testing")
include("documentation")
include("cloud-platform")
include("streaming")
include("graphql")
